import { DadosInfatil } from "@/shared/types";

export const Atletas: DadosInfatil[] = [
  { nome: "Santiago Afonso", faixa: "Amarela", peso: 51, categoria: "Infantil", equipe: "CVA" },
  { nome: "Tiago Faísco", faixa: "Branca", peso: 38, categoria: "Mirim", equipe: "CVA" },
  { nome: "Rosa Getsel", faixa: "Cinza", peso: 31.6, categoria: "Infantil", equipe: "CVA" },
  { nome: "Tiago Kempe", faixa: "Cinza", peso: 45, categoria: "Infanto-Juvenil", equipe: "ATOS São Luís" },
  { nome: "Balian Hellinger", faixa: "Cinza", peso: 64, categoria: "Infanto-Juvenil", equipe: "Atos Jiu-Jitsu" },
  { nome: "Tomas Guia", faixa: "Amarela", peso: 78.4, categoria: "Infantil", equipe: "SampaioBJJ_FCS" },
  { nome: "Heitor Pereira", faixa: "Branca", peso: 56, categoria: "Infanto-Juvenil", equipe: "Academia DL BJJ" },
  { nome: "Moussa Rashed", faixa: "Branca", peso: 31, categoria: "Mirim", equipe: "Odojo Sao Luis" },
  { nome: "Samuel Rosa", faixa: "Laranja", peso: 50, categoria: "Infanto-Juvenil", equipe: "DL-BJJ QUELUZ" },
  { nome: "Samuel Rosa", faixa: "Laranja", peso: 50, categoria: "Infantil", equipe: "DL-BJJ QUELUZ" },
  { nome: "NOAH LOPEZ", faixa: "Branca", peso: 38, categoria: "Infantil", equipe: "O dojo do Sao Luis" },
  { nome: "LEON LOPEZ", faixa: "Branca", peso: 30, categoria: "Mirim", equipe: "O dojo do Sao Luis" },
  { nome: "Emanuel Rosa", faixa: "Cinza", peso: 38, categoria: "Mirim", equipe: "DL-BJJ QUELUZ" },
  { nome: "Thallyson Vasconcelos", faixa: "Azul", peso: 72, categoria: "Juvenil", equipe: "ZR team Sintra" },
  { nome: "Gabriel Inácio Krushovski", faixa: "Amarela", peso: 49.3, categoria: "Infanto-Juvenil", equipe: "Ícone jiu jitsu Algarve" },
  { nome: "Francisco Ferreira", faixa: "Branca", peso: 25.3, categoria: "Mirim", equipe: "CVA" },
  { nome: "Alície Vermelho", faixa: "Branca", peso: 20.5, categoria: "Pré-Mirim", equipe: "CVA" },
  { nome: "Simão Alexandrino", faixa: "Cinza", peso: 28.8, categoria: "Mirim", equipe: "CVA" },
  { nome: "Margarida Mestre", faixa: "Cinza", peso: 19.7, categoria: "Mirim", equipe: "CVA" },
  { nome: "Mara Rebolo", faixa: "Branca", peso: 23.6, categoria: "Mirim", equipe: "CVA" },
  { nome: "Ana Cunha", faixa: "Branca", peso: 58.5, categoria: "Infanto-Juvenil", equipe: "CVA" },
  { nome: "Carolina Lança", faixa: "Cinza", peso: 28.1, categoria: "Infantil", equipe: "CVA" },
  { nome: "Iara Guerreiro", faixa: "Branca", peso: 55.5, categoria: "Infantil", equipe: "CVA" },
  { nome: "Fabiana Guerreiro", faixa: "Branca", peso: 49.8, categoria: "Infantil", equipe: "CVA" },
  { nome: "Louis Gana", faixa: "Branca", peso: 57.7, categoria: "Infanto-Juvenil", equipe: "CVA" },
  { nome: "Maliah Noack", faixa: "Branca", peso: 55, categoria: "Infantil", equipe: "CVA" },
  { nome: "Samuel Savador", faixa: "Branca", peso: 31, categoria: "Infantil", equipe: "Sampaiobjj-fcs Algarve" },
  { nome: "Lea Salazar", faixa: "Cinza", peso: 45, categoria: "Infantil", equipe: "O Dojo São Luís"},
  { nome: "Salvador Balicevic", faixa: "Amarela", peso: 52.55, categoria: "Infanto-Juvenil", equipe: "Icon jiujitsu Algarve"},
  { nome: "Diego soares", faixa: "Cinza", peso: 24.50, categoria: "Mirim", equipe: "Icon jiu jitsu algarve"},
  { nome: "Moritz Fajan Hänsel ", faixa: "Cinza", peso: 54, categoria: "Infanto-Juvenil", equipe: "Atos  Sao Luis"},
  { nome: "Liedson Arrulo", faixa: "Branca", peso: 56, categoria: "Infanto-Juvenil", equipe: "Bragança Essence internacional"},
  { nome: "Telma Rodrigues", faixa: "Verde", peso: 60, categoria: "Infanto-Juvenil", equipe: "Fighters Inside Regunegos de Monsaraz"},
  { nome: "William Machado", faixa: "Branca", peso: 64, categoria: "Infanto-Juvenil", equipe: "Endless Team Algés"},
  { nome: "Daniel Reis", faixa: "Branca", peso: 36.7, categoria: "Infantil", equipe: "CVA"},
  { nome: "Lucía Thaler", faixa: "Cinza", peso: 50, categoria: "Infanto-Juvenil", equipe: "ATOS"},
  { nome: "Simão Chá", faixa: "Branca", peso: 83, categoria: "Juvenil", equipe: "Fighters Inside"},
  { nome: "Lennad Lengfeld", faixa: "Cinza", peso: 45, categoria: "Infanto-Juvenil", equipe: "Atos Jiu-Jitsu São Luís"},
  { nome: "Lucas Bezerra", faixa: "Verde", peso: 65, categoria: "Infanto-Juvenil", equipe: "Zrteam casal de cambra"},
  { nome: "Louis Pinheiro", faixa: "Cinza", peso: 53, categoria: "Juvenil", equipe: "ATOS São Luis"},
  { nome: "João Pereira ", faixa: "Amarela", peso: 43, categoria: "Infanto-Juvenil", equipe: "Zrteam casal de cambra"},
  { nome: "Liedson Arrulo ", faixa: "Amarela", peso: 60, categoria: "Infanto-Juvenil", equipe: "Essencial internacional"},
  { nome: "Ryo Elsinga", faixa: "Amarela", peso: 64, categoria: "Infanto-Juvenil", equipe: "Odojo odemira s.Luis"    },
  { nome: "Margarida Pereira", faixa: "Cinza", peso: 38, categoria: "Infantil", equipe: "Cobrinha Portugal"    },
  { nome: "Gabriela Pereira", faixa: "Cinza", peso: 25, categoria: "Pré-Mirim", equipe: "Cobrinha Portugal"    },
  { nome: "Mia Menezes", faixa: "Branca", peso: 18, categoria: "Mirim", equipe: "Roger Gracie Algarve"    },
  { nome: "Luanda Menezes", faixa: "Branca", peso: 28, categoria: "Mirim", equipe: "Roger Gracie Algarve"    },
  { nome: "David Menezes", faixa: "Branca", peso: 47, categoria: "Infanto-Juvenil", equipe: "Roger Gracie Algarve"    }
  { nome: "Henrique Santos", faixa: "Cinza", peso: 28.5, categoria: "Mirim", equipe: "Zr Team"    }
  { nome: "Joana Manhita", faixa: "Cinza", peso: 46, categoria: "Mirim", equipe: "Cobrinha Portugal"    }
  { nome: "Santiago Fialho", faixa: "Cinza", peso: 33, categoria: "Mirim", equipe: "Cobrinha Portugal"    }
];