import { DadosAdulto } from "@/shared/types";

export const Atletas: DadosAdulto[] = [
    { nome: "Jonas Rodrigues", equipe: "CVA BJJ", sexo: "Masculino", categoria: "Master 3", peso: "Pesado", faixa: "Preta" },
    { nome: "Cassio Gomes", equipe: "Fight Club", sexo: "Masculino", categoria: "Master 1", peso: "Super-Pesado", faixa: "Preta" },
    { nome: "ANDRÉ ALMEIDA", equipe: "SAMPAIO BJJ", sexo: "Masculino", categoria: "Master 3", peso: "Pesadíssimo", faixa: "Branca" },
    { nome: "Gabriel Piçarra", equipe: "Bear bones", sexo: "Masculino", categoria: "Adulto", peso: "Pena", faixa: "Azul" },
    { nome: "Roman", equipe: "Familia Marola Algarve", sexo: "Masculino", categoria: "Master 2", peso: "Médio", faixa: "Branca" },
    { nome: "Helder Silva", equipe: "Academia Mente Blindada, Algueirao Mem Martins", sexo: "Masculino", categoria: "Adulto", peso: "Pesado", faixa: "Preta" },
    { nome: "Rodrigo Silva", equipe: "CVABJJ", sexo: "Masculino", categoria: "Adulto", peso: "Pluma", faixa: "Marron" },
    { nome: "Ismael Poeta", equipe: "Família Marola Algarve", sexo: "Masculino", categoria: "Master 3", peso: "Médio", faixa: "Azul" },
    { nome: "Diane Grossot", equipe: "Bear bones", sexo: "Feminino", categoria: "Master 3", peso: "Médio", faixa: "Azul" },
    { nome: "João Oliveira", equipe: "Kaishi Jiu Jitsu Lagoa", sexo: "Masculino", categoria: "Adulto", peso: "Pesadíssimo", faixa: "Branca" },
    { nome: "Elena Buss", equipe: "Bear Bones", sexo: "Feminino", categoria: "Master 2", peso: "Médio", faixa: "Azul" },
    { nome: "André Pinto", equipe: "CVA BJJ", sexo: "Masculino", categoria: "Master 1", peso: "Leve", faixa: "Roxa" },
    { nome: "Márcio Vieira", equipe: "Sampaio FCS BJJ", sexo: "Masculino", categoria: "Adulto", peso: "Médio", faixa: "Azul" },
    { nome: "Débora Cabrita", equipe: "Sampaio BJJ", sexo: "Feminino", categoria: "Adulto", peso: "Meio-Pesado", faixa: "Azul" },
    { nome: "Miguel Roma", equipe: "Sampaio BJJ_FCS", sexo: "Masculino", categoria: "Adulto", peso: "Médio", faixa: "Branca" },
    { nome: "Rafael Ferreira", equipe: "Kaishi Jiu Jitsu Lagoa", sexo: "Masculino", categoria: "Adulto", peso: "Pesado", faixa: "Azul" },
    { nome: "Nuno Ferreira", equipe: "Kaishi Jiu Jitsu Lagoa", sexo: "Masculino", categoria: "Master 3", peso: "Super-Pesado", faixa: "Azul" },
    { nome: "Marlon Espada", equipe: "Família Marola Algarve", sexo: "Masculino", categoria: "Master 2", peso: "Leve", faixa: "Azul" },
    { nome: "Carlos Santillan Blanco", equipe: "Bear Bones Aljezur", sexo: "Masculino", categoria: "Master 3", peso: "Médio", faixa: "Azul" },
    { nome: "Afonso Leite", equipe: "SampaioBJJ", sexo: "Masculino", categoria: "Adulto", peso: "Leve", faixa: "Branca" },
    { nome: "Giovanni Capella", equipe: "Familia Marola Algarve", sexo: "Masculino", categoria: "Master 1", peso: "Leve", faixa: "Preta" },
    { nome: "Eduardo Polo", equipe: "Bear Bones Jiu Jitsu", sexo: "Masculino", categoria: "Adulto", peso: "Leve", faixa: "Branca" },
    { nome: "Miklos de Pina ", equipe: "CVA BJJ", sexo: "Masculino", categoria: "Adulto", peso: "Médio", faixa: "Branca" },
    { nome: "Jéssica Martins", equipe: "Sampaio BJJ", sexo: "Feminino", categoria: "Master 1", peso: "Pena", faixa: "Azul" },
    { nome: "Zango Edgar Gonçalves", equipe: "Fighclubesantarem", sexo: "Masculino", categoria: "Adulto", peso: "Médio", faixa: "Roxa" },
    { nome: "Elias Martins", equipe: "Kaishi Jiu Jitsu Lagoa", sexo: "Masculino", categoria: "Adulto", peso: "Médio", faixa: "Branca" },
    { nome: "Guilgerme Gonçalves", equipe: "Kaishi Jiu Jitsu Lagoa", sexo: "Masculino", categoria: "Adulto", peso: "Pluma", faixa: "Azul" },
    { nome: "Helder Silva", equipe: "Mente Blindada", sexo: "Masculino", categoria: "Adulto", peso: "Meio-Pesado", faixa: "Preta" },
    { nome: "Leonardo Gana", equipe: "CVA BJJ", sexo: "Masculino", categoria: "Master 4", peso: "Leve", faixa: "Branca" },
    { nome: "Melyssa Botelho", equipe: "Familia Marola Algarve", sexo: "Feminino", categoria: "Adulto", peso: "Pena", faixa: "Branca" },
    { nome: "Nuno Pedro", equipe: "SampaioBJJ", sexo: "Masculino", categoria: "Master 3", peso: "Pesadíssimo", faixa: "Roxa" },
    { nome: "Elvis Silva", equipe: "Fight Studio Beja", sexo: "Masculino", categoria: "Master 1", peso: "Meio-Pesado", faixa: "Branca" },
    { nome: "Guilherme Gonçalves", equipe: "Kaishi Jiu Jitsu Lagoa", sexo: "Masculino", categoria: "Adulto", peso: "Pluma", faixa: "Azul" },
    { nome: "Alya Martins", equipe: "Bear Bones Jiu Jitsu", sexo: "Femenino", categoria: "Adulto", peso: "Pena", faixa: "Branca" },
    { nome: "Dinis Faustino🏳️‍🌈", equipe: "CVA BJJ", sexo: "Masculino", categoria: "Adulto", peso: "Maio-Pesado", faixa: "Branca" },

];
