import { DadosAdulto } from "@/shared/types";

export const Atletas: DadosAdulto[] = [
  //{ nome: "Filipe Goes", faixa: "Roxa", peso: "Pena", categoria: "Master 1", equipe: "Icon jiu jitsu", sexo: "Masculino" },
  //{ nome: "Eduardo Peixoto", faixa: "Azul", peso: "Leve", categoria: "Master 2", equipe: "5 Element Jiu jitsu Alentejo", sexo: "Masculino" },
  { nome: "Jonas Rodrigues", faixa: "Preta", peso: "Super-Pesado", categoria: "Master 3", equipe: "CVA", sexo: "Masculino" },
  { nome: "Pedro Santinhos", faixa: "Branca", peso: "Médio", categoria: "Master 3", equipe: "5 elements jui-jitsu Alentejo", sexo: "Masculino" },
  //{ nome: "Lauro de Souza", faixa: "Preta", peso: "Super-Pesado", categoria: "Master 1", equipe: "Acreditar Sempre Jiu-Jitsu", sexo: "Masculino" },
  { nome: "Rodrigo Silva", faixa: "Roxa", peso: "Pluma", categoria: "Adulto", equipe: "CVA", sexo: "Masculino" },
  //{ nome: "David Lima", faixa: "Preta", peso: "Leve", categoria: "Master 4", equipe: "AJA JIU JITSU ASSOCIATION", sexo: "Masculino" },
  { nome: "Cristian Salazar", faixa: "Roxa", peso: "Médio", categoria: "Master 1", equipe: "Atos Alentejo" , sexo: "Masculino"},
  { nome: "Pedro Silva", faixa: "Branca", peso: "Médio", categoria: "Adulto", equipe: "DLL BJJ QUELUZ", sexo: "Masculino" },
  //{ nome: "Márcio Vieira", faixa: "Branca", peso: "Meio-Pesado", categoria: "Adulto", equipe: "Sampaio", sexo: "Masculino" },
  { nome: "Glaucilene Oliveira", faixa: "Azul", peso: "Médio", categoria: "Master 2", equipe: "Sampaiobjj _FSC-Algarve", sexo: "Feminino" },
  //{ nome: "George Gomes", faixa: "Azul", peso: "Médio", categoria: "Master 1", equipe: "Gracie Barra Paços de Arcos", sexo: "Masculino" },
  { nome: "André pinto", faixa: "Azul", peso: "Leve", categoria: "Master 1", equipe: "CVA", sexo: "Masculino" },
  { nome: "Carlos Silva", faixa: "Azul", peso: "Médio", categoria: "Master 1", equipe: "Sampaio bjj", sexo: "Masculino" },
  { nome: "Ana Porto", faixa: "Azul", peso: "Pena", categoria: "Adulto", equipe: "Sampaio BJJ FCS Algarve", sexo: "Feminino" },
  { nome: "Moustafa Rashed", faixa: "Branca", peso: "Pesadíssimo", categoria: "Master 3", equipe: "Odojo Sao Luis", sexo: "Masculino" },
  { nome: "Geisi Souza", faixa: "Branca", peso: "Leve", categoria: "Adulto", equipe: "Sampaio BJJ FCS Algarve", sexo: "Feminino" },
  //{ nome: "Rui Pinheiro", faixa: "Azul", peso: "Super-Pesado", categoria: "Master 2", equipe: "Familia Andre Marola", sexo: "Masculino" },
  { nome: "Tymur Zakirov", faixa: "Branca", peso: "Médio", categoria: "Master 1", equipe: "ACADEMIA DL BJJ", sexo: "Masculino" },
  { nome: "Guilherme Cruz", faixa: "Branca", peso: "Pesado", categoria: "Adulto", equipe: "Academia DL-BJJ", sexo: "Masculino" },
  //{ nome: "George Gomes", faixa: "Azul", peso: "Médio", categoria: "Master 1", equipe: "Gracie Barra Paços de Arcos", sexo: "Masculino" },
  //{ nome: "André Matos", faixa: "Branca", peso: "Pena", categoria: "Adulto", equipe: "Sampaio Algarve", sexo: "Masculino" },
  { nome: "Alex Cardeira", faixa: "Roxa", peso: "Médio", categoria: "Adulto", equipe: "DL-bjj", sexo: "Masculino" },
  { nome: "David Mendes", faixa: "Azul", peso: "Pluma", categoria: "Adulto", equipe: "Família Marola Faro", sexo: "Masculino" },
  { nome: "Débora Cabrita", faixa: "Branca", peso: "Meio-Pesado", categoria: "Adulto", equipe: "Sampaio bjj", sexo: "Feminino" },
  { nome: "Atanas N. Krushovski", faixa: "Marron", peso: "Pesado", categoria: "Master 4", equipe: "Icon jiu jitsu Algarve", sexo: "Masculino" },
  //{ nome: "Luís Martins", faixa: "Roxa", peso: "Super-Pesado", categoria: "Master 5", equipe: "Sampaio bjj_fcs", sexo: "Masculino" },
  //{ nome: "Hugo Tavares", faixa: "Preta", peso: "Meio-Pesado", categoria: "Master 3", equipe: "Endless Team Jiu Jitsu", sexo: "Masculino"},
  { nome: "Bruno Carvalho", faixa: "Azul", peso: "Médio", categoria: "Master 1", equipe: "Endless Team", sexo: "Masculino" },
  { nome: "Diogo Pinho", faixa: "Branca", peso: "Médio", categoria: "Master 2", equipe: "Endless Jiu Jitsu Algés", sexo: "Masculino"},
  { nome: "Diogo Godinho", faixa: "Branca", peso: "Pena", categoria: "Adulto", equipe: "ZR Team Sintra", sexo: "Masculino" },
  { nome: "Leonardo Gana", faixa: "Branca", peso: "Médio", categoria: "Master 2", equipe: "CVA", sexo: "Masculino"},
  { nome: "Henrique Silvestre", faixa: "Branca", peso: "Médio", categoria: "Adulto", equipe: "CVA", sexo: "Masculino"},
  //{ nome: "António Pereira", faixa: "Branca", peso: "Leve", categoria: "Master 1", equipe: "O Dojo São Luís", sexo: "Masculino"},
  { nome: "Carlos Teixeira", faixa: "Azul", peso: "Médio", categoria: "Master 1", equipe: "Figthers inside", sexo: "Masculino"},
  { nome: "Alexandre Rodrigues", faixa: "Branca", peso: "Pesado", categoria: "Adulto", equipe: "Checkmat torres Vedras", sexo: "Masculino"},
  //{ nome: "Bruno Sodre", faixa: "Branca", peso: "Pesado", categoria: "Master 1", equipe: "Gracie lisboa", sexo: "Masculino"},
  { nome: "Luís Verdades", faixa: "Azul", peso: "Leve", categoria: "Master 1", equipe: "Endless Team-Liga de Algés", sexo: "Masculino"},
  { nome: "Helder Sousa", faixa: "Marron", peso: "Pesado", categoria: "Master 1", equipe: "Endless", sexo: "Masculino"},
  { nome: "Rui Gomes", faixa: "Azul", peso: "Pena", categoria: "Master 2", equipe: "Endless Team Liga de Algés", sexo: "Masculino"},
  { nome: "Francisco Ferreira", faixa: "Azul", peso: "Pluma", categoria: "Adulto", equipe: "Checkmate Europa", sexo: "Masculino"},
  { nome: "Samer Haidar", faixa: "Azul", peso: "Meio-Pesado", categoria: "Master 1", equipe: "Odojo Sao luis", sexo: "Masculino"},
  //{ nome: "Alexandre Sousa", faixa: "Branca", peso: "Pesado", categoria: "Adulto", equipe: "Peposo Team Portugal", sexo: "Masculino"},
  //{ nome: "Pedro Tarabá", faixa: "Marron", peso: "Médio", categoria: "Adulto", equipe: "Academia 21 BPT Queluz", sexo: "Masculino"},
  { nome: "Ricardo Gomes", faixa: "Preta", peso: "Meio-Pesado", categoria: "Master 3", equipe: "BPT internacional", sexo: "Masculino"},
  { nome: "Marcos Almeida", faixa: "Branca", peso: "Pesadíssimo", categoria: "Adulto", equipe: "BPT internacional", sexo: "Masculino"},
  //{ nome: "Sergio Júnior", faixa: "Azul", peso: "Pesado", categoria: "Adulto", equipe: "Wish roll Porto", sexo: "Masculino"},
  //{ nome: "Alemão ", faixa: "Marron", peso: "Médio", categoria: "Master 1", equipe: "ZR Team Casal de Cambra", sexo: "Masculino"  },
  //{ nome: "Carlos Diogo", faixa: "Roxa", peso: "Pena", categoria: "Master 3", equipe: "ZR Team Casal de Cambra", sexo: "Masculino"},
  { nome: "João Silva", faixa: "Branca", peso: "Médio", categoria: "Adulto", equipe: "Icon Jiu Jitsu Carcavelos", sexo: "Masculino"},
  //{ nome: "Arlindo Prates", faixa: "Preta", peso: "Meio-Pesado", categoria: "Adulto", equipe: "Icon Jiu Jitsu Algarve", sexo: "Masculino"},  
  //{ nome: "Maria Ferreira", faixa: "Marron", peso: "Médio", categoria: "Adulto", equipe: "Gracie Barra Portimão", sexo: "Feminino"},  
  //{ nome: "Rafael Santos", faixa: "Branca", peso: "Meio-Pesado", categoria: "Adulto", equipe: "Luso Warrior Alcântara", sexo: "Masculino"},  
  //{ nome: "Antonio Filho", faixa: "Marron", peso: "Pesadíssimo", categoria: "Master 4", equipe: "Monteiro, Brasil", sexo: "Masculino"},  
  //{ nome: "José Vicente", faixa: "Azul", peso: "Médio", categoria: "Master 1", equipe: "Brasa Lisboa", sexo: "Masculino"  },
  { nome: "Carlos Luz", faixa: "Azul", peso: "Pesado", categoria: "Adulto", equipe: "CVABJJ", sexo: "Masculino"},
  { nome: "Rui Bernardo", faixa: "Azul", peso: "Médio", categoria: "Adulto", equipe: "Fighters Inside Portugal", sexo: "Masculino"},
  { nome: "Antonio Acabado", faixa: "Branca", peso: "Pena", categoria: "Adulto", equipe: "Fighters Inside", sexo: "Masculino"},
  //{ nome: "João Acabado", faixa: "Branca", peso: "Pesado", categoria: "Adulto", equipe: "Fighters Inside", sexo: "Masculino"},
  { nome: "Pedro Rodrigues", faixa: "Preta", peso: "Super-Pesado", categoria: "Master 3", equipe: "Fighters Inside", sexo: "Masculino"},
  //{ nome: "Mayron Souza", faixa: "Azul", peso: "Meio-Pesado", categoria: "Master 1", equipe: "2Brothers Monte Caparica", sexo: "Masculino"},
  { nome: "Nuno pedro", faixa: "Azul", peso: "Pesado", categoria: "Master 4", equipe: "Sampaio", sexo: "Masculino" }, 
  { nome: "Carlos Nunes", faixa: "Marron", peso: "Pena", categoria: "Master 2", equipe: "Cobrinha", sexo: "Masculino"},
  { nome: "Daniel Lincoln", faixa: "Branca", peso: "Médio", categoria: "Master 1", equipe: "Endless Team Jiu Jitsu", sexo: "Masculino"  },  
  //{ nome: "Gonçalo Pereira", faixa: "Marron", peso: "Leve", categoria: "Adulto", equipe: "Brazilian Power Team", sexo: "Masculino"  },  
  //{ nome: "Daniel Hoeger", faixa: "Azul", peso: "Pena", categoria: "Adulto", equipe: "Artsuave Marcão", sexo: "Masculino"  },  
  //{ nome: "Victor fiaes", faixa: "Branca", peso: "Pluma", categoria: "Adulto", equipe: "Karkara bjj caldas da rainha", sexo: "Masculino"  },  
  //{ nome: "Nuno pedro", faixa: "Azul", peso: "Pesado", categoria: "Master 4", equipe: "Sampaio", sexo: "Masculino"  },  
  { nome: "Rubben Rocha", faixa: "Roxa", peso: "Médio", categoria: "Adulto", equipe: "Katsu Jiu-Jitsu", sexo: "Masculino"  },  
  //{ nome: "Leandro Pinheiro", faixa: "Roxa", peso: "Leve", categoria: "Master 2", equipe: "Reginaldo Avelino", sexo: "Masculino"  },  
  { nome: "Sérgio Aires", faixa: "Branca", peso: "Leve", categoria: "Master 2", equipe: "CVA", sexo: "Masculino"  },  
  { nome: "Alexandre Policarpo", faixa: "Branca", peso: "Médio", categoria: "Master 1", equipe: "CVA", sexo: "Masculino"  },  
  //{ nome: "Anderson", faixa: "Preta", peso: "Meio-Pesado", categoria: "Master 1", equipe: "Bjj4life", sexo: "Masculino"  },  
  { nome: "Joana Costa", faixa: "Branca", peso: "Meio-Pesado", categoria: "Adulto", equipe: "CVA", sexo: "Feminino"  },
  //{ nome: "Deyveson Oliveira", faixa: "Preta", peso: "Pesadíssimo", categoria: "Adulto", equipe: "Black Norte Jiu-jitsu", sexo: "Masculino"},
  { nome: "Tiago Silva", faixa: "Roxa", peso: "Pesadíssimo", categoria: "Master 1", equipe: "DL BJJ Queluz", sexo: "Masculino"},
  //{ nome: "Cesario santana", faixa: "Roxa", peso: "Médio", categoria: "Master 1", equipe: "Gracie Barra Portimao", sexo: "Masculino"},
  //{ nome: "Tiago nunes", faixa: "Azul", peso: "Leve", categoria: "Adulto", equipe: "Icon jiu-jitsu Cascais", sexo: "Masculino"},
  { nome: "Samuel Pãozinho", faixa: "Azul", peso: "Pesadíssimo", categoria: "Master 2", equipe: "Icon JJ Team", sexo: "Masculino"  },  
  { nome: "Guilherme Gonçalves", faixa: "Branca", peso: "Pena", categoria: "Adulto", equipe: "Icon Jiu-Jitsu Algarve", sexo: "Masculino"  },  
  { nome: "Pedro Confeiteiro", faixa: "Azul", peso: "Leve", categoria: "Adulto", equipe: "Five Elements", sexo: "Masculino"  }, 
  { nome: "Miguel Carvalho", faixa: "Azul", peso: "Leve", categoria: "Adulto", equipe: "Icon Jiu-Jitsu Évora", sexo: "Masculino"  },  
  { nome: "Joana Rocha", faixa: "Azul", peso: "Meio-Pesado", categoria: "Adulto", equipe: "Vita Team Évora", sexo: "Feminino"  },  
  { nome: "Alexandre silva", faixa: "Branca", peso: "Médio", categoria: "Master 2", equipe: "Gracie barra Hamburgo", sexo: "Masculino"  },
  //{ nome: "Yara leite", faixa: "Marron", peso: "Leve", categoria: "Adulto", equipe: "Endlles team", sexo: "Feminino"  },
  { nome: "Widerley souza", faixa: "Azul", peso: "Pluma", categoria: "Adulto", equipe: "GSampaiobjj Algarve", sexo: "Masculino"  },
  { nome: "José", faixa: "Roxa", peso: "Meio-Pesado", categoria: "Master 2", equipe: "DL-Bjj", sexo: "Masculino" },
  { nome: "Miguel Rondão", faixa: "Branca", peso: "Leve", categoria: "Adulto", equipe: "Academia DL-BJJ", sexo: "Masculino"  },
  { nome: "Alexei Lungu", faixa: "Roxa", peso: "Meio-Pesado", categoria: "Adulto", equipe: "Sampaio BJJ", sexo: "Masculino"  },
  { nome: "Tiago Gomes", faixa: "Branca", peso: "Médio", categoria: "Adulto", equipe: "DL Jiu-jitsu -  Queluz", sexo: "Masculino"  },
  { nome: "Leonardo Silva", faixa: "Roxa", peso: "Meio-Pesado", categoria: "Master 1", equipe: "Roger Gracie Algarve", sexo: "Masculino"  },
  { nome: "Elena Buss", faixa: "Branca", peso: "Meio-Pesado", categoria: "Adulto", equipe: "Roger Gracie Algarve", sexo: "Feminino"  },
  { nome: "Anne van Es", faixa: "Branca", peso: "Leve", categoria: "Adulto", equipe: "Roger Gracie Algarve", sexo: "Feminino"  },
  //{ nome: "Evany Ottoniel", faixa: "Marron", peso: "Pena", categoria: "Master 1", equipe: "Gracie Barra Amora", sexo: "Masculino"  },
  //{ nome: "João Domingos Oliveira", faixa: "Azul", peso: "Pena", categoria: "Adulto", equipe: "Under Pressure BJJ", sexo: "Masculino"  },
  { nome: "Guilherme Seabra", faixa: "Branca", peso: "Pena", categoria: "Adulto", equipe: "Checkmat Europa", sexo: "Masculino"  },
  { nome: "Jorge Nunes", faixa: "Roxa", peso: "Médio", categoria: "Master 4", equipe: "BPT Internacional", sexo: "Masculino"  },
  { nome: "Tiago Batista", faixa: "Azul", peso: "Pluma", categoria: "Adulto", equipe: "Icon Jiu-Jitsu Team", sexo: "Masculino"  },
  { nome: "Gabriel Mota", faixa: "Azul", peso: "Pluma", categoria: "Adulto", equipe: "DL BJJ Queluz", sexo: "Masculino"  },
  { nome: "João Martins", faixa: "Branca", peso: "Leve", categoria: "Adulto", equipe: "Cobrinha Portugal, Beja", sexo: "Masculino"  },
  { nome: "Sérgio Albuquerque", faixa: "Azul", peso: "Meio-Pesado", categoria: "Master 3", equipe: "Academia DL-BJJ Queluz", sexo: "Masculino"  },
  { nome: "Victor Dicov", faixa: "Branca", peso: "Leve", categoria: "Master 2", equipe: "Cobrinha Portugal", sexo: "Masculino"  },
  { nome: "Diane Grossot", faixa: "Azul", peso: "Médio", categoria: "Master 2", equipe: "Roger Gracie Algarve", sexo: "Feminino"  },   
  { nome: "Bruno Soares", faixa: "Azul", peso: "Pena", categoria: "Master 2", equipe: "Roger Gracie Algarve", sexo: "Masculino"  },  
  { nome: "Bruno Ataíde", faixa: "Azul", peso: "Pesadíssimo", categoria: "Master 2", equipe: "Roger Gracie Algarve", sexo: "Masculino"  },  
  { nome: "Gonçalo Alegre", faixa: "Azul", peso: "Leve", categoria: "Adulto", equipe: "Roger Gracie Algarve", sexo: "Masculino"  },  
  { nome: "José Vilhena", faixa: "Branca", peso: "Leve", categoria: "Adulto", equipe: "cvabjj", sexo: "Masculino"  },  
  { nome: "João Dias", faixa: "Azul", peso: "Leve", categoria: "Master 1", equipe: "Icon jiu-jitsu team", sexo: "Masculino"  },  
  { nome: "Daniele Réus", faixa: "Azul", peso: "Pena", categoria: "Adulto", equipe: "Família Marola (Faro)", sexo: "Feminino"  },
  { nome: "Miguel  Silvino", faixa: "Preta", peso: "Médio", categoria: "Master 4", equipe: "Clone bjj", sexo: "Masculino"  },
  { nome: "Elias Leal", faixa: "Azul", peso: "Super-Pesado", categoria: "Master 2", equipe: "Clone bjj", sexo: "Masculino"  },
  { nome: "Ericles godoi", faixa: "Azul", peso: "Pesado", categoria: "Adulto", equipe: "Clone bjj", sexo: "Masculino"  },
  { nome: "Carlos Sequeira Guerreiro ", faixa: "Marron", peso: "Pesado", categoria: "Master 4", equipe: "CVA", sexo: "Masculino"  },
  //{ nome: "Paulo Júlio ", faixa: "Marron", peso: "Médio", categoria: "Master 4", equipe: "Clone bjj", sexo: "Masculino"  },
  { nome: "Pedro Catarino ", faixa: "Azul", peso: "Leve", categoria: "Master 1", equipe: "Endless Team", sexo: "Masculino"  },
  { nome: "Tauan Fabiano", faixa: "Roxa", peso: "Meio-Pesado", categoria: "Master 1", equipe: "Gracie Barra", sexo: "Masculino"  },
  //{ nome: "Tiago Gorges", faixa: "Marron", peso: "Pesadíssino", categoria: "Master 2", equipe: "Icon Jiu Jitsu", sexo: "Masculino"  },
  { nome: "Bianca Rocha", faixa: "Branca", peso: "Super-Pesado", categoria: "Adulto", equipe: "Família Marola Faro", sexo: "Feminino"  },
  { nome: "Apolo Pereira", faixa: "Branca", peso: "Médio", categoria: "Master 1", equipe: "Old Dog", sexo: "Masculino"  },
  { nome: "Ricardo Viegas", faixa: "Azul", peso: "Leve", categoria: "Master 1", equipe: "Old Dog", sexo: "Masculino"  },
  { nome: "Cristiano Hortensio", faixa: "Azul", peso: "Leve", categoria: "Adulto", equipe: "Old Dog", sexo: "Masculino"  },
  { nome: "Cristiano Pereira", faixa: "Roxa", peso: "Super-Pesado", categoria: "Master 1", equipe: "Old Dog", sexo: "Masculino"  },
  { nome: "Ana Silva", faixa: "Branca", peso: "Super-Pesado", categoria: "Adulto", equipe: "Old Dog", sexo: "Feminino"  },
  { nome: "Paula Oliveira", faixa: "Azul", peso: "Pena", categoria: "Adulto", equipe: "Old Dog", sexo: "Feminino"  },
  { nome: "Matheus Maier", faixa: "Preta", peso: "Médio", categoria: "Master 1", equipe: "Família Marola Faro", sexo: "Masculino"  },
  { nome: "Thallyson Vasconcelos", faixa: "Azul", peso: "Leve", categoria: "Adulto", equipe: "ZR Team Sintra", sexo: "Masculino"  },
  { nome: "Thavyne Kayla", faixa: "azul", peso: "Pena", categoria: "Adulto", equipe: "ZR Team Sintra", sexo: "Feminino"  },
  { nome: "Daiane Alexandra", faixa: "azul", peso: "Meio-Pesado", categoria: "Adulto", equipe: "ZR Team Sintra", sexo: "Feminino"  },

];
